version: "2"

linters:
  default: none
  enable:
    - logmsglint

  settings:
    custom:
      logmsglint:
        type: module
        description: Checks slog/go.uber.zap log messages to basic style and safety rules.
        settings:
          enable_fixes: true             # enable fixes (for example for lowercase)
          allowed_punct: ""              # special symbols is forbidden
          sensitive_keywords:            # you can add your own keywords here
            - "secret_token"
          sensitive_regexps:           # you can add your own regex-patterns here
            - "(?i)api[_-]?key\\s*="